### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by dinojr** [geigerzaehler/beets-alternatives#12]
You propose:
`beet modify onplayer=true artist:Bach`
Shouldn't it be:
`beet modify artist:Bach onplayer=true` ?
According to the beets documentation, the QUERY should precede the modification:
`beet modify [-MWay] [-f FORMAT] QUERY [FIELD=VALUE...] [FIELD!...]`

**Comment by geigerzaehler** [comment]
Despite the command documentation `beet` allows you to specify query and modifications in any order. That means the command in the Readme is perfectly fine.
