### ISSUE TITLE
Create m3u for newly imported tracks 

### ISSUE THREAD

**Issue by sindreruud** [geigerzaehler/beets-alternatives#45]
First of all, thank you so much for this plugin. It has saved me countless hours in my music management!

One feature I think would make this even more useful would be functionality from the already existing "ImportFeeds" plugin: https://beets.readthedocs.io/en/stable/plugins/importfeeds.html

I use beets-alternatives to create a smaller version of my library to use with Rekordbox (DJ software). Rekordbox supports importing new tracks through a m3u file, XML file or drag&drop. 

If beets-alternatives could create an m3u file containing absolute paths, each time you did "beet alt update myplayer", that would be amazing. There is probably other clients out there that can also utilize m3u files for importing new music. But I realize that this might be a limited use case. Thought I would propose it as a feature request anyway. 

Again, thank you so much to everyone that has contributed to this plugin, (almost) literally a life saver for me.

**Comment by geigerzaehler** [comment]
Thanks for your request, @sindreruud. I think we can tackle your use case but I’d like to suggest an alternative solution that would be more bare bones and would work for a broader set of use cases:

We implement a `beet alt list <COLLECTION>` that lists all the items that are part of the given collection. We would support the `--format` and `--path` options just like [`beet list`](https://beets.readthedocs.io/en/v1.4.9/reference/cli.html#list).

Running this command with `--path` after `beet alt update` should be enough to generate a m3u playlist. Can you see this working for you?

**Comment by sindreruud** [comment]
More bare bones to cater for a broader audience seems very reasonable, and I can see that being more valuable. After looking into the m3u syntax, it shouldn't be hard at all to generate them if beets-alternatives gets a list function. 

Thanks for looking into this!
