### ISSUE TITLE
Enhancement: Embed artwork when converting formats.

### ISSUE THREAD

**Issue by BSteinmetz** [geigerzaehler/beets-alternatives#5]
My music library is mostly FLAC and I am using beets-alternatives to maintain a folder of songs in MP3 format for my iPhone/iPod. When beets-alternatives converts the songs to MP3, it would be nice if it embedded the album artwork at the same time. The 'embedart' plugin already exists, so maybe you can tie into that? Or this could already be possible and I am just missing it.

**Comment by geigerzaehler** [comment]
Thanks for your suggestion, @BSteinmetz. This feature is now available in [v0.8.1](https://github.com/geigerzaehler/beets-alternatives#v081---2015-05-30).
